---
include:
#  - board: nice_nano_v2
#    shield: eyeslash_corne_central_dongle prospector_adapter
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
#     artifact-name: eyeslash_corne_central_dongle
  - board: nice_nano_v2
    shield: lily58_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: lily58_dongle_oled
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right
  - board: nice_nano_v2
    shield: settings_reset
